spring:
  main:
    banner-mode: off

  datasource:
    url: jdbc:mysql://localhost:3306/employee_office
    username: root
    password: Fredom1808

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

#  logging:
#    level:
#      root: DEBUG

  sql:
    init:
      schema-locations:
        classpath: db/schema.sql
      data-locations:
        classpath: db/data.sql

#  liquibase:
#    change-log: classpath:/db/changelog-master.xml
