server:
  port: 8080
spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:mysql://localhost:3306/employee_office?allowMultiQueries=true
    username: root
    password: Fredom1808
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: classpath:/db/changelog/v0.0.1-SNAPSHOT/changelog.xml


logging:
  level:
    root: info

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: alpha
    tagsSorter: alpha



