server:
  port: 8080
spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:employee_office}?allowMultiQueries=true
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:Fredom1808}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: classpath:/db/changelog/v0.0.1-SNAPSHOT/changelog.xml

  mvc:
    static-path-pattern: /static/**


logging:
  level:
    root: info

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: alpha
    tagsSorter: alpha





