spring:
  main:
    banner-mode: off

  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  sql:
    init:
      schema-locations:
        classpath:db/schema.sql
      data-locations:
        classpath:db/data.sql
      mode: always
#logging:
#  level:
#    root: WARN



#  liquibase:
#    change-log: classpath:/db/changelog-master.xml
