server:
  port: 8080
spring:
  main:
    banner-mode: off



  datasource:
    url: jdbc:mysql://localhost:3306/employee_office
    username: root
    password: Fredom1808

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none



  sql:
    init:
      schema-locations: classpath:db/changelog/v0.0.1-SNAPSHOT/init-db.sql
      data-locations: classpath:db/changelog/v0.0.1-SNAPSHOT/data.sql
      mode: always




#//${DATASOURCE_URL}
#//${DATASOURCE_USERNAME}
#//${DATASOURCE_PASSWORD}

#// open-in-view: false